[Reference](https://medium.com/@dan_bishop/power-bi-live-dashboard-with-python-9a5ccae363c3)

In [1]:
pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.1.70-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Collecting lxml>=4.5.1
  Downloading lxml-4.9.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 6.1 MB/s
Collecting requests>=2.26
  Downloading requests-2.28.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.7 MB/s
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2022.5.18.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.0.12)
Installing collected packages: requests, lxml, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.28.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed lxml-4.9.0 requests-2.28.0 yfinance-0.1.70

In [2]:
import yfinance as yf
import pandas as pd

In [3]:
#Creating Ticker() Object
ticker = yf.Ticker('PLTR')

In [4]:
#Creating cash flow table for Power BI
#Creating data frame & formatting
cashflow_df = ticker.cashflow.transpose().reset_index().rename(columns={'':'Year'})
#Changing data types
cashflow_df['Year']= cashflow_df['Year'].astype(str).str[:4]
#Finding free cash flow
cashflow_df['Free Cash Flow'] = cashflow_df['Total Cash From Operating Activities'] + cashflow_df['Capital Expenditures']

In [5]:
cashflow_df.head()

,Year,Investments,Change To Liabilities,Total Cashflows From Investing Activities,Net Borrowings,Total Cash From Financing Activities,Change To Operating Activities,Issuance Of Stock,Net Income,Change In Cash,Effect Of Exchange Rate,Total Cash From Operating Activities,Depreciation,Other Cashflows From Investing Activities,Change To Account Receivables,Other Cashflows From Financing Activities,Change To Netincome,Capital Expenditures,Repurchase Of Stock,Free Cash Flow
0,2021,-382265000.0,82499000.0,-397912000.0,-200000000.0,3.067470e+08,-139314000.0,5.074550e+08,-5.203790e+08,238768000.0,-3918000.0,333851000.0,14897000.0,-3020000.0,-35237000.0,-708000.0,9.313850e+08,-12627000.0,NaN,321224000.0
1,2020,-2934000.0,-65586000.0,-14920000.0,-200631000.0,1.036453e+09,-259672000.0,1.241358e+09,-1.166391e+09,726184000.0,1259000.0,-296608000.0,13871000.0,250000.0,-108476000.0,-497000.0,1.289646e+09,-12236000.0,-3777000.0,-308844000.0
2,2019,-8868000.0,-110972000.0,-21964000.0,394413000.0,3.245330e+08,276103000.0,1.168970e+08,-5.796460e+08,135127000.0,-2227000.0,-165215000.0,12255000.0,250000.0,-23905000.0,-1202000.0,2.609500e+08,-13096000.0,-11202000.0,-178311000.0
3,2018,-8868000.0,184712000.0,-6784000.0,-56491000.0,4.615400e+07,128346000.0,1.091510e+08,-5.800270e+08,-3345000.0,-3703000.0,-39012000.0,13910000.0,250000.0,-10483000.0,1200000.0,2.245300e+08,-15404000.0,-7706000.0,-54416000.0